<?php
$page_title="Register"; include("includes/header.php"); $message="";
if(isset($_POST["register"])) {
 require_csrf(); $name=safe_field($_POST["name"]); $email=strtolower(safe_field($_POST["email"])); $password=(string)$_POST["password"]; $confirm=(string)$_POST["confirm"]; $address=safe_field($_POST["address"]); $contact=safe_field($_POST["contact"]);
 if($name===""||$email===""||$password===""||$address===""||$contact===""){$message="Please complete every field.";} elseif(!filter_var($email,FILTER_VALIDATE_EMAIL)){$message="Enter a valid email address.";} elseif(strlen($password)<8){$message="Use at least 8 characters for your password.";} elseif($password!==$confirm){$message="Passwords do not match.";} elseif(isset(find_row("users.txt",2,$email)[0])){$message="That email is already registered.";} else {$id=time(); append_row("users.txt",array($id,$name,$email,password_hash($password,PASSWORD_DEFAULT),$address,$contact,"buyer")); audit("Registered account " . $email); redirect_box("login.php","Registration successful. You can now sign in.");}
}
?>
<section class="auth-layout"><div><span class="eyebrow">Join MediNest</span><h1>Create your account.</h1><p>Save your details and move through checkout more smoothly.</p></div><form class="panel form" method="post"><?php echo csrf_field(); ?><h2>Buyer registration</h2><?php if($message!="") echo '<div class="notice">'.h($message).'</div>'; ?><label>Complete name<input name="name" autocomplete="name" required></label><label>Email address<input name="email" type="email" autocomplete="email" required></label><div class="two"><label>Password<input name="password" type="password" minlength="8" autocomplete="new-password" required></label><label>Confirm password<input name="confirm" type="password" minlength="8" autocomplete="new-password" required></label></div><label>Complete address<textarea name="address" autocomplete="street-address" required></textarea></label><label>Contact number<input name="contact" autocomplete="tel" required></label><button class="button full" name="register">Create account</button><p class="form-note">Already registered? <a href="login.php">Sign in</a></p></form></section>
<?php include("includes/footer.php"); ?>
